[colors.primary]
background = "#1d1f28"
foreground = "#d4d6df"

[colors.normal]
black = "#141620"
red = "#e27878"
green = "#b4be82"
yellow = "#e2a478"
blue = "#84a0c6"
magenta = "#a093c7"
cyan = "#89b8c2"
white = "#d4d6df"

[colors.bright]
black = "#4b4f63"
red = "#e27878"
green = "#b4be82"
yellow = "#e2a478"
blue = "#84a0c6"
magenta = "#a093c7"
cyan = "#89b8c2"
white = "#eceef7"
